logger:
  level: info
  format: text # color, json, text
  app_path: "./logs/app.log"
  health_path: "./logs/health.log"
  http_path: "./logs/http.log"
  kafka_path: "./logs/kafka.log"
  minio_path: "./logs/minio.log"
  task_path: "./logs/task.log"
  s3_path: "./logs/s3.log"
  max_size: 10 # максимальный размер файла в мегабайтах (0 = без ограничений)
  max_files: 5 # максимальное количество файлов (0 = без ограничений)
  clear_on_start: true # очищать ли файл при старте приложения
  mode: files #files, stdout

server:
  port: 8080
  host: "0.0.0.0"
  prefork: false
  timeout: 30s
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s
  max_file_size: 10485760  # 10MB в байтах
  max_file_count: 10       # максимальное количество файлов для многофайловой загрузки

database:
  host: "localhost"
  port: 5443
  user: "postgres"
  password: "postgres"
  database: "task_manager"
  max_connections: 25
  min_connections: 5
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m

broker:
  bootstrap_service: "localhost:9092"
  client_id: "task_manager_1_client"
  topics:
    - tasks_llm
    # - tasks_analysis

  # Producer
  producer_acks: "-1"
  producer_idempotence: true
  producer_compression: "none"
  producer_retries: 3
  producer_batch_size: 16384
  producer_linger_ms: 10
  producer_max_flight_requests: 5
  producer_timeout_ms: 30000

  # Consumer
  consumer_group_id: "task_llm_group"
  consumer_auto_commit: true
  consumer_commit_interval_ms: 5000
  consumer_session_timeout_ms: 30000
  consumer_heartbeat_interval_ms: 10000
  consumer_max_poll_records: 500

  # Security #В прод лучше заменить на SASL_PLAINTEXT и указать username и password
  security_protocol: "PLAINTEXT"
  sasl_mechanism: ""
  sasl_username: ""
  sasl_password: ""

  # SSL
  ssl_certificate_verification: false

metrics:
  enabled: true
  port: 9091
  host: "0.0.0.0"
  path: "/metrics"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "documents"
  prefix: "uploads"
  UseSSL: false
  Region: "us-east-1"
  Timeout: 30s

swagger:
  enabled: true
  path: "/swagger"

tasks:
  - type: "llm"
    name: "LLM Processing Task"
    topic: "tasks_llm"
    workers: 5
    timeout: 300s
    max_retries: 3
    queue_size: 1000
    storage_path: "llm/"
    enabled: true
