// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/multiupload": {
            "post": {
                "description": "Загружает несколько файлов и создает задачу на их обработку.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "multiupload"
                ],
                "summary": "Создать задачу для загрузки нескольких файлов",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файлы для загрузки (множественная загрузка)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Задача успешно создана",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_restapi_v1_multiupload.CreateMultiUploadTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании задачи",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{filename}": {
            "post": {
                "description": "Загружает файл в бинарном формате и создает задачу на обработку.",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Создать задачу обработки файла (streaming upload)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя файла с расширением. Пример: document.pdf",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Размер файла в байтах. Устанавливается автоматически при использовании curl --data-binary",
                        "name": "Content-Length",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Бинарное содержимое файла",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Задача успешно создана",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_restapi_v1.SwaggerCreateTaskSuccess"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании задачи",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{task_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_restapi_v1.SwaggerGetTaskSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_internal_entity_domain.TaskStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED"
            ],
            "x-enum-varnames": [
                "TaskStatusPending",
                "TaskStatusProcessing",
                "TaskStatusCompleted",
                "TaskStatusFailed",
                "TaskStatusCancelled"
            ]
        },
        "app_pkg_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_restapi_v1.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/app_internal_entity_domain.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_restapi_v1.GetTaskResponse": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/app_internal_entity_domain.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                },
                "task_results": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_handlers_restapi_v1.SwaggerCreateTaskSuccess": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handlers_restapi_v1.CreateTaskResponse"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_restapi_v1.SwaggerGetTaskSuccess": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handlers_restapi_v1.GetTaskResponse"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_restapi_v1_multiupload.CreateMultiUploadTaskResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/app_internal_entity_domain.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
